### PR TITLE
Shrink by 46 bytes

### PR DESCRIPTION
**Pull request by chris-morgan**
Brevity is king.

### CODE REVIEW

**Comment by chris-morgan** [comment]
If you want to put those 36 bytes to a good purpose instead of cutting the size down, we can make it valid HTML 5:

``` html
<!DOCTYPE html><title>X</title><script>s=0,t=Date.now()</script><p onclick="(e=Date.now()-t)<15e3?style.margin=++s+e%300+'px':alert(s)">X
```

This takes it out of quirks mode, so the `<p>` has initial top and bottom margins (an actual visual change) and a unit is required when setting `style.margin`.

**Comment by nbjorken** [comment]
If you cache the Date.now function you can save another 3 bytes.

``` html
<script>s=0,d=Date.now,t=d()</script><p onclick="(e=d()-t)<15e3?style.margin=++s+e%300:alert(s)">X
```

Edit: Oh, you committed that as I was writing the comment @chris-morgan :)

**Comment by chris-morgan** [comment]
@nbjorken I already realised I’d missed that one and did it.

**Comment by joevennix** [comment]
You can save a byte using `id`:

```
<p id=a onclick="if(a)s=0,d=Date.now,t=d();a=0,(e=d()-t)<15e3?style.margin=++s+e%300:alert(s)">X
```

**Comment by chris-morgan** [comment]
@nbjorken Nice idea with `<body onload>`, that one hadn’t occurred to me.

**Comment by thorrez** [comment]
It still seems to work if quotes are removed.

```
<body onload=s=0,d=Date.now,t=d()><p onclick=(e=d()-t)<15e3?style.margin=++s+e%300:alert(s)>X
```

**Comment by chris-morgan** [comment]
@thorrez Yeah, the quotes still being around are an artefact of my valid HTML 5 edition, where because of the `=` they are needed. (Most people don’t seem to realise that most of the time the quotes around an attribute are not necessary for valid HTML. I have what some would consider to be an appalling habit of normally omitting the quotes where possible. Ditto with closing tags for things like `<p>` and `<li>`.) In quirks mode, however—

**Comment by chris-morgan** [comment]
@joevennix That’s a nifty technique, but it changes the semantics.

**Comment by clockworknazo** [comment]
You can save a byte when initializing s: `t=d(s=0)`

**Comment by chris-morgan** [comment]
@tokyograph I like it! `t=(d=Date.now)(s=0)` would work too, for the same length…

**Comment by naugtur** [comment]
a little shorter:

``` html
<p onclick=n=Date.now;id||(t=n(id=s=0));(e=n(++s)-t)<2E4?style.margin=e%300:alert(s)>X
```

the idea is - if we can access style without `this`, why not access `id` - shortest attribute possible - to safely check if it's the first call. the part after `id||` will be executed only the first time. assigning 0 to `id` causes it to be truthy. why? `id` is a string and DOM converts the 0 to string

**Comment by chris-morgan** [comment]
@nbjorken: a trivial change in semantics to something that’s probably more desirable anyway, 👍.

@naugtur: that’s two significant changes in semantics, both starting the timer on the first click rather than page load and going for 20 seconds rather than 15 seconds, 👎.

**Comment by naugtur** [comment]
Change 2e4 to 15e3 and it's back to 15 sec. Starting on the first click is a feature suggestion ;) I thought it'd be more fair anyway (I'm a 'open in a new tab in background' kind of guy)

**Comment by clockworknazo** [comment]
If you're allowing changes to the margin calculation, why not this? This even makes the game more challenging, since the margin is now more unpredictable (it depends on the current time rather than the elapsed time).
`<body onload=t=15e3+(d=Date.now)(s=0)><p onclick=d()<t?style.margin=d(++s)%300:alert(s)>X`
And this would be the body only version:
`<body onload=t=15e3+(d=Date.now)(s=0) onclick=d()<t?style.margin=d(++s)%300:alert(s)>X`

**Comment by nbjorken** [comment]
There is still the bug where you are able to click on the rest of the line of the p element. If you change it from p to an inline element the margins don't work properly. This is the shortest I can figure out where clicking to the right of X is not a valid gameplay input.

``` html
<img onerror=t=15e3+(d=Date.now)(s=0) onclick=d()<t?style.margin=d(++s)%300:alert(s) src=a>
```

Now, it's not really an X, but the broken image icon. I guess in older versions of IE it would actually be an X ;)

**Comment by clockworknazo** [comment]
@nbjorken If you really want an X, you can do it with 4 more bytes. (There may be a box around the X, depending on the browser.)

```
<img onerror=t=15e3+(d=Date.now)(s=0) onclick=d()<t?style.margin=d(++s)%300:alert(s) alt=X src>
```

**Comment by nbjorken** [comment]
@tokyograph nice! Looks a lot better! But 4 bytes is a lot to me right now. I need to have a long, hard think.

**Comment by akoluthic** [comment]
Wow - waking up to a big PR this morning, thanks everyone!  My two main priorities, given how small it's gotten, would be to fix the bug where you can click the entire line, and to have enough space left to generate different margins for the top and left, so the X doesn't just move diagonally but all around the 300x300 game space.  I think I have a version that works but I'd like to merge this first unless anyone is still working on something.

**Comment by chris-morgan** [comment]
@tokyograph

> This even makes the game more challenging, since the margin is now more unpredictable (it depends on the current time rather than the elapsed time).

It’s done modulo 300 (milliseconds) so there’s no practical difference—like the difference between a sine wave and a cosine wave, it’s just a matter of the starting point.

@omnus: go ahead, I’ve taken this as far as I think it should go in pure minification. Time to spice it up with improved features!

**Comment by nbjorken** [comment]
Here is a stab at one, 106 chars, where you cannot invoke the entire line, and where x/y positions will take different values after each click.

``` html
<img onerror=t=15e3+(d=Date.now)(s=0,m=300) onclick=d()<t?vspace=d(++s,hspace=s*t%m)%m:alert(s) alt=X src>
```

This does not work in Firefox. Firefox requires src to have a value, and it won't honor the vspace value.

**Comment by clockworknazo** [comment]
@chris-morgan I just meant that you could "practice" a pattern for the elapsed-time version since it will always follow the same pattern (if you can perfect your timing), while you won't know the starting point for the current-time version (unless you always start at the same time % 5min).

@nbjorken Very nice! vspace not working in Firefox is a bummer, though. Margin/padding will be a lot more expensive :( Anyway, you can improve this by 2 bytes.

```
<img onerror=t=15e3+(d=Date.now)(s=0,m=300) onclick=d()<t?vspace=d(hspace=++s*t%m)%m:alert(s) alt=X src>
```

**Pull request merged**
